registry:
  grit:
    name: GritLM/GritLM-7B
    hidden_dim: 4096
    metric: cosine_similarity
    # batch_size: 128
    batch_size: 128

  contriever:
    name: facebook/contriever-msmarco
    hidden_dim: 768
    metric: inner_product
    batch_size: 256

  bm25:
    name: bm25
    hidden_dim: 768
    metric: inner_product
    batch_size: 256
